Repository kabianca/social-network, pull requests merged in 2022-09, with the labels that each got.

#11 Iniciando o readme
  README.md
  cooking.png
  package.json
  readme-feedbacks-ux.png
  readme-prototipo-alta-fidelidade-mobile1.png
  readme-prototipo-baixa-fidelidade-mobile.png
  thumb.png
Labels: documentation

#19 Ajuste css login
  src/pages/login/login.css
  src/pages/register/register.css
  src/pages/timeline/timeline.css
  src/pages/timeline/timeline.js
Labels: style

#22 atualização readme
  README.md
Labels: documentation

#30 Correcao eslint
  package.json
  src/lib/auth.js
  src/lib/config.js
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/register/register.js
  src/pages/timeline/timeline.js
  src/validations.js
Labels: behavior

#34 erros e validacoes de inputs
  src/lib/firestore.js
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/register/register.css
  src/pages/register/register.js
  src/pages/timeline/timeline.js
Labels: user experience, behavior

#38 Inicio testes
  src/lib/__mocks__/exports.js
  src/lib/auth.js
  src/lib/config.js
  src/lib/exports.js
  test/auth.spec.js
Labels: behavior

#39 teste chamar redirect timeline com botao google ok
  src/lib/__mocks__/exports.js
  src/lib/auth.js
  src/main.js
  src/pages/login/login.js
  src/pages/register/register.js
  src/redirect.js
  test/auth.spec.js
  test/pages/login.spec.js
Labels: behavior

#40 Desktop
  src/assets/background desktop.jpg
  src/pages/login/login.css
  src/pages/register/register.css
  src/pages/timeline/timeline.css
  src/pages/timeline/timeline.js
Labels: style

#46 correcao do outro commit
  src/lib/firestore.js
  src/pages/timeline/recipe.css
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.css
  src/pages/timeline/timeline.js
Labels: style, data, behavior
