Repository kabianca/social-network, pull requests merged in 2022-10, with the labels that each got.

#52 print de todos as receitas ao entrar na timeline
  src/lib/exports.js
  src/lib/firestore.js
  src/main.js
  src/pages/login/login.css
  src/pages/register/register.css
  src/pages/timeline/post.js
  src/pages/timeline/recipe.css
  src/pages/timeline/timeline.css
  src/pages/timeline/timeline.js
Labels: style, skeleton, behavior

#53 print post funcionando refresh na pag eslint com 1 erro
  src/lib/config.js
  src/lib/firestore.js
  src/main.js
  src/pages/timeline/post.js
  src/pages/timeline/recipe.css
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.js
Labels: behavior

#54 Add funcao like/deslike
  src/lib/exports.js
  src/lib/firestore.js
  src/main.js
  src/pages/timeline/post.js
  src/pages/timeline/printRecipes.js
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.js
Labels: behavior

#56 print posts funcionando com erro
  src/pages/timeline/printRecipes.js
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.css
Labels: behavior

#57 editar postagem e ordem decrescente data
  src/index.css
  src/lib/exports.js
  src/lib/firestore.js
  src/pages/timeline/editRecipe.js
  src/pages/timeline/post.js
  src/pages/timeline/recipe.css
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.css
  src/pages/timeline/timeline.js
Labels: style, skeleton, behavior

#59 teste firestore print/like/deslike
  src/lib/__mocks__/exports.js
  src/lib/firestore.js
  src/pages/timeline/post.js
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.js
  test/pages/timeline.spec.js
Labels: behavior

#60 Ajuste css
  src/index.css
  src/index.html
  src/lib/firestore.js
  src/pages/login/login.css
  src/pages/login/login.js
  src/pages/register/register.css
  src/pages/register/register.js
  src/pages/timeline/editRecipe.js
  src/pages/timeline/post.css
  src/pages/timeline/post.js
  src/pages/timeline/recipe.css
  src/pages/timeline/recipe.js
  src/pages/timeline/timeline.css
  src/pages/timeline/timeline.js
  test/pages/timeline.spec.js
Labels: style, design
